(function(){
	angular.module('myApp',['ui.router',
							'ngResource',
							'routeModule',
							'myFilter',
							'authcInteceptorModule',
							'directiveModule',
							'mainCtrlModule'
	]);	
})();